
const AboutUsText = "O que fazemos é com dedicação, voluntariedade e amor aos animais. \n Iniciamos nossas atividades no ano de 2000, através da  iniciativa de pessoas interessadas no bem estar dos animais, preocupadas com os maus tratos sofridos pelos mesmos, sempre causados pelos ser humano. \n Esperamos poder contar com a sua ajuda! Àqueles que nos auxiliam, o nosso muito obrigado!";
const Services = "Segunda à Sexta" + "\n" + "8h30 às 17h" + " Sábados" + "\n" + "9h às 12h";
const ContactNum1 = "41 3032-5205";
const ContactNum2 = "41 99934-0673";
const Surgeries = "A clínica veterinária da Protetora dos Animais de Campo Largo oferece consultas, vacinas e cirurgias, facilitando o cuidado com o seu pet. Uma parte dos valores cobrados ajuda a custear o atendimento veterinário a animais abandonados."
const Address = "Rua 21 de Abril 45, Campo Largo, 83607-482";
const Responsable = " Técnico Dr. Daniel Luis dos Anjos CRMV-PR 11.351";
const Email = "moresaadv@onda.com.br";
const Vaccines = 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.';
const Queries = 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.';
const AboutDonation = "Nós da Associação Protetora de Animais de Campo Largo mantemos animais para adoção em nossa casa. Caso você tenha condições financeiras e queira adotar um de nossos animais, sinta-se a vontade para nos contatar. Nessa aba listamos em tempo real alguns de nossos animais que estão vivendo aqui na casa e algumas informações sobre eles. Caso não possa adotar, você pode se tornar madrinha ou padrinho de um bixinho ajudando simbolicamente a casa e os animais de sua preferência! "
const AboutBottleCapDonation = "Aceitamos tampinhas, tampas plásticas e lacres qualquer tipo e tamanho. Você pode nos entregar diretamente em nossa sede ou, dependendo da distância e disponibilidade, podemos buscar em algum local a combinar. Entre em contato no número 41 98479-9073 para verificar a disponibilidade para agendamento do recolhimento. Pedimos por gentileza que você separe os materiais a serem recolhidos por tipo para facilitar na venda desses objetos."
const AboutReceiptDonation = "Aceitamos notas fiscais para doações. Para que consigamos pegar os recursos dessa nota ela deve ter sido emitida a menos de 30 dias, ou seja, caso você tenha interesse em nos ajudar com as notas fiscais precisamos que elas tenham ausência de CPF e emitidas em um intervalo de tempo inferior a 30 dias. Você pode levar as suas notas fiscais até nossa sede ou entrar em contato."
export { AboutReceiptDonation, Email, AboutUsText, Services, ContactNum1, ContactNum2, Surgeries, Address, Responsable, Vaccines, Queries, AboutDonation, AboutBottleCapDonation }  